### ISSUE TITLE
not really issue just question

### ISSUE THREAD

**Issue by SERVANTSKILL** [Ruuv1337/RTP_IX#11]
Hi again man, so sorry to keep bother your like this but im wonder if this is works?
[image](https://imgur.com/52hbK56)

is able use temp pet upgrade normal level 10 pet to partner? or just upgrade partner fellowship? or is not usable function and in testing 😅 

thank you thank you so much again for response!

**Comment by Ruuv1337** [comment]
Hi, I don’t know how many experience points this will give.
I just left it if someone suddenly wants to transform it into an experience for other permanent pets.

**Comment by SERVANTSKILL** [comment]
oo so its for level pets but not works on partner? i tried level partner pet with buff but not works, also tried to combine normal pets to turn partner but not works too hahaha

**Comment by Ruuv1337** [comment]
I made some fixes
try, maybe it will work.

**Comment by SERVANTSKILL** [comment]
hi am sorry late response, just back from work 😄 just tried it not seems work

**Comment by Ruuv1337** [comment]
So probably not working anymore.
