### ISSUE TITLE
[RTP Notice] unmapped packet "S_REQUEST_SERVANT_INFO_LIST 3" !!!

### ISSUE THREAD

**Issue by asdfghjk-op** [Ruuv1337/RTP_IX#14]
Hi,

I have **S_REQUEST_SERVANT_INFO_LIST = 29440** mapped into **protocol.369048.map** but the console is still giving me this error:

**[RTP Notice] unmapped packet "S_REQUEST_SERVANT_INFO_LIST 3" !!!**

Is there a missing def or is the opcode mapped incorrectly?

Thanks.

**Comment by Ruuv1337** [comment]
hello, try put file in a folder "TeraToolbox\data\definitions"

link del

**Comment by asdfghjk-op** [comment]
That fixed the issue with the unmapped packet, but now I'm getting this issue: 

![rtportissue](https://user-images.githubusercontent.com/67249593/85314508-8b72f780-b4b1-11ea-8596-f330824162fb.PNG)

**Comment by Ruuv1337** [comment]
try this one.
it should have been updated automatically if you have the latest version of TeraToolbox

**Comment by MarinoPachino** [comment]
Does this work for pinkie pie's proxy?

**Comment by Ruuv1337** [comment]
> 
> 
> Does this work for pinkie pie's proxy?

working

**Comment by asdfghjk-op** [comment]
> try this one.
> it should have been updated automatically if you have the latest version of TeraToolbox
> link del

Tried this too and doesn't seem to work with Pinkie Pie's proxy. Getting this error now:
![image](https://user-images.githubusercontent.com/67249593/85356964-37dfc880-b508-11ea-8b4a-1c27bca0d5c9.png)

**Comment by Ruuv1337** [comment]
try this
[S_REQUEST_SERVANT_INFO_LIST.4.zip](https://github.com/Ruuv1337/RTPort/files/4818494/S_REQUEST_SERVANT_INFO_LIST.4.zip)

**Comment by asdfghjk-op** [comment]
> try this
> [S_REQUEST_SERVANT_INFO_LIST.4.zip](https://github.com/Ruuv1337/RTPort/files/4818494/S_REQUEST_SERVANT_INFO_LIST.4.zip)

Getting this error now:
14:56:23 Error: [tera-proxy-game] [dispatch] handle: failed to parse S_SPAWN_USER<15>

**Comment by Ruuv1337** [comment]
> 
> 
> > try this
> > [S_REQUEST_SERVANT_INFO_LIST.4.zip](https://github.com/Ruuv1337/RTPort/files/4818494/S_REQUEST_SERVANT_INFO_LIST.4.zip)
> 
> Getting this error now:
> 14:56:23 Error: [tera-proxy-game] [dispatch] handle: failed to parse S_SPAWN_USER<15>

this is a "tera-proxy-game" mod error
I think you need to update your proxy

**Comment by asdfghjk-op** [comment]
> > > try this
> > > [S_REQUEST_SERVANT_INFO_LIST.4.zip](https://github.com/Ruuv1337/RTPort/files/4818494/S_REQUEST_SERVANT_INFO_LIST.4.zip)
> > 
> > 
> > Getting this error now:
> > 14:56:23 Error: [tera-proxy-game] [dispatch] handle: failed to parse S_SPAWN_USER<15>
> 
> this is a "tera-proxy-game" mod error
> I think you need to update your proxy

That worked, ty
