### ISSUE TITLE
Does it still work?

### ISSUE THREAD

**Issue by MarinoPachino** [Ruuv1337/RTP_IX#15]
Does infinite sorc arcane pulse still work? If it does how do I get it to work?

**Comment by Nezlac** [comment]
> Does infinite sorc arcane pulse still work? If it does how do I get it to work?

you need to be awakened first
write in /8
rtp - (your email)
then write sr enable
then use ur basic attack too spam pulses (LMB by default)

**Comment by MarinoPachino** [comment]
okay thank you everything is solved :)
