### ISSUE TITLE
update for p97?

### ISSUE THREAD

**Issue by asdfghjk-op** [Ruuv1337/RTP_IX#17]
hi will u update for the new patch?

**Comment by Ruuv1337** [comment]
There were no problems with the new 64 bit patch.
If you think that one of the possibilities may have stopped working, please indicate it here for verification.

**Comment by asdfghjk-op** [comment]
sorry i did not see this.the rtpe function is currently not working

**Comment by Ruuv1337** [comment]
Log on 09.08.20
    The ability to synthesize pets from a take no longer works and has been removed.
