### ISSUE TITLE
everything works, but I have a mod request

### ISSUE THREAD

**Issue by RTX-hub** [Ruuv1337/RTP_IX#19]
Hello, is it possible to rework this module https://github.com/Ruuv1337/tera-arcanepulse-spam to spam another type of arcane pulse and not the one with mana boost buff? I'm trying to level up a sorc from lvl 1 but obviously i cant use the module without being lvl 65. Also what's your discord tag?

**Comment by Ruuv1337** [comment]
Hey, you should contact author of this mod.
Also, after a recent update, this is not relevant.
https://github.com/salchy-lab/tera-arcanepulse-spam
