### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by sasorifunny** [Ruuv1337/RTP_IX#7]
Hello, how i buy this hack and how much price? Thx for answer)

**Comment by Ruuv1337** [comment]
hey, price for premium func. is 20euro per month. Before paying, write to me in Discord.

**Comment by sasorifunny** [comment]
> hey, price for premium func. is 20euro per month. Before paying, write to me in Discord.

thx for answer, nice price, but i have another question, can you add the function of freezing the speed of your character so that he runs in battle at the same speed as outside the battle? I used to use such a cheat, but I would like you to add it to yours and I will become a regular customer. Thanks in advance. And sorry for my english :)

**Comment by Ruuv1337** [comment]
Do you have this mod?
Suitable even if it does not work.

**Comment by sasorifunny** [comment]
> Do you have this mod?
> Suitable even if it does not work.

its not mod, its cheat, but yes i have source code, I bought it, but I'm not a programmer and do not understand much.

**Comment by Ruuv1337** [comment]
It would be great to take a look, if possible, send me it to Discord. And with high probability I can add it. If it is not encrypted. 
In any case, you can connect both scripts to TeraToolbox, I think ..

**Comment by sasorifunny** [comment]
add me in discord ◥▶_◀◤#5944 and i give you source code this cheat, in my hands, it is still useless, and you are sure to come up with something. This is a full cheat with different functions, but the only thing that interests me is the speed freeze :)
